apiVersion: v1
kind: Namespace
metadata:
  name: student-api

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: student-api-config
  namespace: student-api
data:
  FLASK_PORT: "5001"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-api
  namespace: student-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-api
  template:
    metadata:
      labels:
        app: student-api
    spec:
      containers:
      - name: student-api
        image: <docker-image>
        envFrom:
        - configMapRef:
            name: student-api-config
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DATABASE_URL
        ports:
        - containerPort: 5001

---
apiVersion: v1
kind: Service
metadata:
  name: student-api-service
  namespace: student-api
spec:
  selector:
    app: student-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5001
  type: ClusterIP
