apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: student-api
type: Opaque
stringData:
  MYSQL_USER: root
  MYSQL_PASSWORD: Admin@123

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: student-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      initContainers:
      - name: mysql-migrations
        image: <migration-image>  
        command: ["sh", "-c", "python run_migrations.py"]
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          value: student_db
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        ports:
        - containerPort: 3306
